#!/usr/bin/env perl
# Copyright (c) 2023 by Manuel Oetiker. All rights reserved
use strict;
use warnings;

my %replacements = (
    'BE' => 'Business_Email',
    'PE' => 'Professional_Edition',
    'SE' => 'Standard_Edition'
);

sub fix {
   my $string = shift;
   $string =~ s/Business_Email/BusiEmail/g;
   $string =~ s/Professional_Edition/ProfEmail/g;
   $string =~ s/Standard_Edition/StandEmail/g;
   return $string
}


my $newest_file;
my @files = glob("/opt/zurt/data/mailbox*");
@files = sort { -M $a <=> -M $b } @files;

if (!@files) {
    print "3 \"Zimbra Licenses\" - No license statistic file found\n"; 
    exit;
}

open my $file, '<', $files[0] or die "Could not open file: $!";
my $header = <$file>;


my %count_name_lictype_domain;
my %count_name_lictype;

my %all_lictypes;

while (<$file>) {
    chomp;
    my @columns = split ',';
    my $domains = $columns[1];
    my $lictype = $columns[2];
    
    $lictype = $replacements{$lictype} if exists $replacements{$lictype};

    $count_name_lictype_domain{$domains}{$lictype}++;
    $count_name_lictype{$lictype}++;
    $all_lictypes{$lictype} = 1; # Collect all unique license types
}

close $file;

foreach my $domains (keys %count_name_lictype_domain) {
    print "0 \"Zimbra Licences $domains\" ";
    my @count;
    my @comment;
    foreach my $lictype (keys %all_lictypes) {
        my $count_lictype = $count_name_lictype_domain{$domains}{$lictype} || 0;
        push @count,"$lictype=$count_lictype";
        my $lictype_short = fix $lictype;
        push @comment,"$lictype_short->$count_lictype";
    }
    print join("|",@count);
    print " ";
    print join(", ",@comment);
    print "\n";
 }

print "0 \"Zimbra Licences Summary\" ";
my @count;
my @comment;
foreach my $lictype (keys %all_lictypes) {
    my $count_lictype = $count_name_lictype{$lictype} || 0;
    push @count,"$lictype=$count_lictype";
    my $lictype_short = fix $lictype;
    push @comment,"$lictype_short->$count_lictype";
}
print join("|",@count);
print " ";
print join(", ",@comment);
print "\n";
