#!/bin/perl -w
use strict;
use warnings;

my %replacements = (
    'BE' => 'Business_Email',
    'PE' => 'Professional_Edition',
    'SE' => 'Standard_Edition'
);

my $newest_file;
my @files = glob("/opt/zurt/data/mailbox*");
@files = sort { -M $a <=> -M $b } @files;

open my $file, '<', $files[0] or die "Could not open file: $!";
my $header = <$file>;

my %count_name_lictype_domain;
my %all_lictypes;

while (<$file>) {
    chomp;
    my @columns = split ',';
    my $domains = $columns[1];
    my $lictype = $columns[2];
    
    $lictype = $replacements{$lictype} if exists $replacements{$lictype};

    $count_name_lictype_domain{$domains}{$lictype}++;
    $all_lictypes{$lictype} = 1; # Collect all unique license types
}

close $file;

foreach my $domains (keys %count_name_lictype_domain) {
    print "0 \"Zimbra Licences $domains\" ";
    my $first = 1; # Flag to check if it's the first license type
    foreach my $lictype (keys %all_lictypes) {
        my $count_lictype = $count_name_lictype_domain{$domains}{$lictype} || 0;
        if ($first) {
            print "$lictype=$count_lictype";
            $first = 0; # Set the flag to false after the first license type is printed
        } else {
            print "|$lictype=$count_lictype";
        }
    }
    print " ";
    $first = 1; # Reset the flag for the second loop
    foreach my $lictype (keys %all_lictypes) {
        my $count_lictype = $count_name_lictype_domain{$domains}{$lictype} || 0;
        $lictype =~ s/Business_Email/BusiEmail/g;
        $lictype =~ s/Professional_Edition/ProfEmail/;
        $lictype =~ s/Standard_Edition/StandEmail/;
        if ($first) {
            print " $lictype->$count_lictype";
            $first = 0; # Set the flag to false after the first license type is printed
        } else {
            print " $lictype->$count_lictype";
        }
    }
    print "\n";
}
